(function(){var f=!0,j=!1,k;
function l(a){function b(){e||(e=f,d?c.h.sa=f:c.ga(a))}var c=this,d=j,e=j;c.La=a.useFlashFallback===j?j:!c.i;c.F=a.statBaseURL;c.O=a.guid||a.GUID;c.K=a.confID;c.n=a.viewableConversion;c.Y=a.api&&!(a.api.bridge===a.api.fallbackAPI||a.api._BRIDGE===a.api.fallbackAPI);c.Ga={viewable:"202",undetectable:"270",rendered:"271"};c.Ha=function(c){return a.replaceMacros(c)};c.ka=c.n?a.viewableImpressionURL:"";c.width=parseInt(a.width,10);c.height=parseInt(a.height,10);c.b=242500<=c.width*c.height?0.6*a.viewableImpressionThreshold:
a.viewableImpressionThreshold;c.s=0;c.Ra=j;c.S=a.viewableImpressionTime;c.w=a.customDefinition;c.t=0;c.la=j;c.$=j;c.A=/iP(ad|od|hone)/.test(navigator.userAgent);c.i=c.A||/safari/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&!/android/i.test(navigator.userAgent)&&!/edge/i.test(navigator.userAgent)&&!/phantomjs/i.test(navigator.userAgent);c.D=window.$sf&&window.$sf.ext;c.target=c.c?window.document.getElementById(a.adId):window.parent.document.getElementById(a.adId)||window.frameElement;
c.r=c.P=c.visibility.u;c.L=0;c.Q=(new Date).getTime();c.q=(new Date).getTime();c.d=0;c.e=0;c.m=0;c.Ja=a.secure;c.renderedImpression=a.firedRenderedImpression||j;c.viewableImpression=j;c.undetectableImpression=j;c.ja=0;c.a={visible:0,C:0,hidden:0,G:0};c.J=f;c.dispatchEvent=function(c,b){a.dispatchEvent(c,b)};c.A&&this.ia(window,"scroll",function(){l.prototype.ha=Date.now()});if(a.fver&&a.minflashversion)this.aa=!!a.fver();else{var h=j;this.I||"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&
(h=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));this.aa=h}"no"!==a.pageVisible&&!c.i&&c.j("rendered");c.c&&(c.D?c.f=c.Ia:"undefined"!==typeof window.mozInnerScreenY?(c.ua=c.f,c.f=c.wa):8<=document.documentMode?c.f=c.Ea:c.aa&&!c.V&&c.La&&!document.documentMode&&!c.i?(c.M={},c.ca=0,d=f,c.h={sa:j},c.l=[],c.k=[],c.ba={id:"99",left:"-10000",top:"-1"},window.ftPagefoldFlashListener=function(b){b=b.split("-");c.Aa(b[0],parseInt(b[1],10),a)},c.f=c.Ba,c.va()):(c.g(this.event.ra),
c.n&&(c.j("undetectable"),("no"!==a.pageVisible||!c.i)&&c.j("rendered")),a.addEventListener("visibilitychange",function(a){"no"!==a&&!c.i&&c.j("rendered")}),c.dispatchEvent("advisibility",j)));c.undetectableImpression||(a.addEventListener("adonpage",b),a.addEventListener("backup",b))}
function m(a){var b="";this.F=a.statBaseURL;this.O=a.guid;this.K=a.confID;this.V=/fox/i.test(navigator.appVersion);b=this.c?window.document.referrer:window.parent.document.location;b=escape(String(b).substr(0,200));this.g("314",b)}
function r(){this.K=this.O=this.F="";this.Fa=window!=top;this.c=j;if(this.Fa)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(a){this.c=f}this.V=/fox/.test(navigator.userAgent);this.I=/MSIE/.test(navigator.userAgent);this.i=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}l.prototype=new r;k=l.prototype;
k.event={qa:"301",pa:"302",U:"303",oa:"304",ma:"305",na:"306",T:"307",ra:"308",Qa:"310",Pa:"311",Oa:"312"};k.visibility={o:2,v:1,u:0};k.ha=0;k.W=[50,175,300,600,1200,3E3];
k.ga=function(a){var b=this;b.target=b.target||(b.c?document.getElementById(a.adId):window.parent.document.getElementById(a.adId)||window.frameElement);var c=this.f(),d=this.event.oa;1===c&&!b.w?d=this.event.qa:0<c&&(d=this.event.pa);this.g(d);this.r=this.P=this.ea(c);!a.api||"loading"!==a.api.getState()?this.X(a):a.api.addEventListener("ready",function(){b.X(a)})};
k.R=function(){var a=this,b=(new Date).getTime(),c=b-this.Q-this.d,d=b-this.q-this.e,e=this.f(),h=this.ea(e);a.A&&250<d&&(b-this.ha<d?e=Math.min(this.ja,e):(this.s=0,a.d+=Math.max(0,b-this.q),a.e+=Math.max(0,b-this.q),c=b-this.Q-this.d,d=b-this.q-this.e));if(a.J&&(a.D||a.target.parentNode))this.dispatchEvent("advisibility",100*e),this.undetectableImpression?this.a.G+=d:1==e?this.a.visible+=d:0<e?this.a.C+=d:this.a.hidden+=d,this.w&&(h===this.visibility.o?this.t+=d:this.t<this.S&&(this.t=0),!this.la&&
this.t>=this.S&&(this.P===this.visibility.v?this.g(this.event.U):this.g(this.event.T),this.la=f)),h>this.r&&this.Ka(h),this.L<this.W.length&&this.p(c)>=this.W[this.L]&&(this.za(),this.Q=b,this.d=0,this.L++),a.n&&(!this.Ma&&this.ka)&&(this.s=e>=this.b?this.s+d:0,this.s>=this.S&&(window.Ta=f,this.j("viewable"))),this.q=b,this.e=0,this.ja=e;(a.D||a.target.parentNode)&&((!a.Y||a.Y&&(a.n&&!a.Ma||!a.n&&!a.$))&&a.J)&&setTimeout(function(){a.R()},100)};
k.B=function(a){return"yes"===a||"no"!==a&&(this.c||this.A)};k.X=function(a){var b=this;b.m=b.B(a.pageVisible)?0:(new Date).getTime();b.B(a.pageVisible)&&b.R();a.addEventListener("visibilitychange",function(a){b.B(a)?(b.d+=b.m?(new Date).getTime()-b.m:0,b.e+=b.m?(new Date).getTime()-b.m:0):(b.m=(new Date).getTime(),b.s=0);b.J=b.B(a);"no"!==a&&!b.i&&b.j("rendered");b.R()})};
k.za=function(){var a=[this.p(this.a.visible)];a.push(this.p(this.a.C));a.push(this.p(this.a.hidden));a.push(this.p(this.a.G));this.g("310",a.join("x"));this.a.visible=0;this.a.C=0;this.a.hidden=0;this.a.G=0;this.$=f};k.j=function(a){!this[a+"Impression"]&&this.n&&((new Image).src=this.Ha(this.ka.replace(";271;",";"+this.Ga[a]+";")),this[a+"Impression"]=f,"undetectable"===a&&(this.viewableImpressionFired=f))};
k.Ka=function(a){var b;this.r===this.visibility.u?a===this.visibility.v?b=this.event.ma:a===this.visibility.o&&(b=this.event.na):this.r===this.visibility.v&&(a===this.visibility.o&&!this.w)&&(b=this.event.U,this.P===this.visibility.u&&(b=this.event.T));this.r=a;"undefined"!==typeof b&&this.g(b)};k.f=function(){var a=this.Ca();return this.Z(a,this.fa())};k.wa=function(){var a=this.xa(),b=this.ya();return Math.min(this.ua(),this.Z(a,b))};k.Ia=function(){return this.D.inViewPercentage()/100};
k.da=function(a,b,c){a=(a=/swf/i.test(a.id)&&/ftin/i.test(a.parentNode.id)&&a.parentNode.style.clip.replace(/^.*\(|px|\)/g,""))?a.split(" "):[0,b,c,0];return{top:parseInt(a[0],10),left:parseInt(a[3],10),right:parseInt(a[1],10),bottom:parseInt(a[2],10)}};k.z=function(a){var b=a.getBoundingClientRect(),c={};(a=this.da(a,b.right-b.left,b.bottom-b.top))?(c.top=b.top+a.top,c.left=b.left+a.left,c.right=a.right-a.left+c.left,c.bottom=a.bottom-a.top+c.top):c=b;return c};
k.Ca=function(){var a=this.z(this.target),b=this.c?window.document.body.getBoundingClientRect():window.parent.document.body.getBoundingClientRect(),c=this.fa(),d=c.scrollLeft&&window.getComputedStyle&&b.left-(parseInt(window.parent.getComputedStyle(window.parent.document.body).marginLeft,10)||0)||0,b=c.scrollTop&&window.getComputedStyle&&b.top-(parseInt(window.parent.getComputedStyle(window.parent.document.body).marginTop,10)||0)||0;return window.attachEvent?{x:a.left+c.scrollLeft,y:a.top+c.scrollTop,
width:a.right-a.left,height:a.bottom-a.top}:{x:a.left-d,y:a.top-b,width:a.right-a.left,height:a.bottom-a.top}};
k.fa=function(){var a={scrollLeft:0,scrollTop:0,height:0,width:0},b=!this.c?window.parent:window;b.innerWidth?(a.width=b.innerWidth,a.height=b.innerHeight,a.scrollLeft=b.pageXOffset,a.scrollTop=b.pageYOffset):b.document.documentElement&&b.document.documentElement.clientHeight?(a.width=b.document.documentElement.clientWidth,a.height=b.document.documentElement.clientHeight,a.scrollLeft=b.document.documentElement.scrollLeft,a.scrollTop=b.document.documentElement.scrollTop):b.document.body&&(a.width=
b.document.body.clientWidth,a.height=b.document.body.clientHeight,a.scrollLeft=b.document.body.scrollLeft,a.scrollTop=b.document.body.scrollTop);return a};k.Z=function(a,b){var c=b.scrollLeft,d=b.scrollLeft+b.width,e=b.scrollTop,h=b.scrollTop+b.height,g=a.x,i=a.x+a.width,n=a.y,p=a.y+a.height,t=(i-g)*(p-n),s=0,q;a:switch(f){case e>p:case c>i:case d<g:case h<n:q=f;break a;default:q=j}q||(c=Math.max(c,g),d=Math.min(d,i),e=Math.max(e,n),h=Math.min(h,p),s=(d-c)*(h-e));return Math.floor(100*(s/t))/100};
k.ea=function(a){var b=this.visibility.u;this.w&&a>=this.b?b=this.visibility.o:1===a?b=this.visibility.o:0<a&&(b=this.visibility.v);return b};k.xa=function(){var a=this.z(this.target);return{x:window.mozInnerScreenX+a.left,y:window.mozInnerScreenY+a.top,width:a.right-a.left,height:a.bottom-a.top}};k.ya=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY+98,height:window.outerHeight-71,width:window.outerWidth}};
k.Ea=function(){function a(a,b){var c=0;return c=1>b?0:b<a?0.1:b<d?e:1}var b=0,c=this.N(f);this.z(this.target);var d=0.5===this.b?9:12,e=this.b,h;for(h in c)b+=document.elementFromPoint(c[h].left,c[h].top)?1:0;return 0.5===e?a(5,b):0.5<e?a(8,b):0.39<e?a(6,b):a(4,b)};k.Ba=function(){function a(a,b){var c=0;return c=1>b?0:b<a?0.1:b<d?e:1}var b=0,c=0,d=0.5===this.b?9:12,e=this.b,h;for(h in this.M)b+=this.M[h]<0.8*this.ca?1:0;c=0.5===e?a(5,b):0.5<e?a(8,b):0.39<e?a(6,b):a(4,b);this.ta();return c};
k.ta=function(){for(var a=this.l,b=this.N(),c=b.length;c--;)if(b[c].top!==a[c].top||b[c].left!==a[c].left)this.k[c].style.top=b[c].top+"px",this.k[c].style.left=b[c].left+"px";this.l=b};k.Aa=function(a,b,c){var d=0;"99"===a?this.ca=b:this.M[a]=b;this.h[a]=f;for(var e in this.h)this.h[e]||d++;if(0===d){if(this.k[0])a=this.k;else{a=document.querySelectorAll(".ftFlashPixel");for(b=a.length;b--;)a[b].id.replace("id","");a=void 0}this.k=a;this.ga(c);this.h.Sa=j}};
k.N=function(a){for(var b=this.z(this.target),c=this.da(this.target,b.right-b.left,b.bottom-b.top),d=c.left,c=c.top,e=b.right-b.left,h=b.bottom-b.top,g=[],i=Math.sqrt(this.b),g=[Math.round(e*(1-i)),Math.round(e*(1-this.b)),Math.round(e*this.b),Math.round(e*i)],i=[Math.round(h*(1-i)),Math.round(h*(1-this.b)),Math.round(h*this.b),Math.round(h*i)],g=0.5===this.b?[{id:"0",left:0,top:i[0]},{id:"1",left:0,top:i[3]},{id:"2",left:g[0],top:0},{id:"3",left:g[0],top:h-1},{id:"4",left:e/2,top:h/2},{id:"5",left:g[3],
top:0},{id:"6",left:g[3],top:h-1},{id:"7",left:e-1,top:i[0]},{id:"8",left:e-1,top:i[3]}]:[{id:"0",left:0,top:i[0]},{id:"1",left:0,top:i[3]},{id:"2",left:g[0],top:0},{id:"3",left:g[0],top:h-1},{id:"4",left:g[1],top:i[1]},{id:"5",left:g[1],top:i[2]},{id:"6",left:g[2],top:i[1]},{id:"7",left:g[2],top:i[2]},{id:"8",left:g[3],top:0},{id:"9",left:g[3],top:h-1},{id:"10",left:e-1,top:i[0]},{id:"11",left:e-1,top:i[3]}],e=g.length;e--;)a?(g[e].left+=b.left,g[e].top+=b.top):(g[e].left+=d,g[e].top+=c);return g};
k.va=function(){function a(a){var b,d="position: absolute; top: "+a.top+"px;",i=this.Da(a.id),d=d+(" width: "+this.H.width+"px;"),d=d+(" height: "+this.H.height+"px;"),d=d+(" left : "+a.left+"px; z-index: -1;");this.I?(b=c.replace("@STYLE@",d).replace("@FLASH@",i).replace("@ID@",a.id),this.target.parentNode.insertAdjacentHTML("beforeend",b)):(b=document.createElement("div"),b.style.cssText=d,b.innerHTML=i,this.target.parentNode.appendChild(b),this.k[a.id]=b)}function b(){a.call(d,d.ba);d.h[d.ba.id]=
j;for(var b=0,c=d.l.length;b<c;b++)d.h[d.l[b].id]=j,a.call(d,d.l[b])}var c='<div id="id@ID@" class="ftFlashPixel" style="@STYLE@">@FLASH@</div>',d=this;this.target.getBoundingClientRect();this.l=this.N();document.body?b():this.ia(document,"readystatechange",function(){document.body&&b()})};
k.Da=function(a){var b=this.H(),c=b.name+a,d;d="<OBJECT "+(this.I?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+b.path+'" type="application/x-shockwave-flash"');d=d+(' ID="'+c+'" name="'+c+'"')+(' width="'+b.width+'" height="'+b.height+'" style="float:left;">');d+='<PARAM NAME=movie VALUE="'+b.path+'"/>';d+='<PARAM NAME=FlashVars VALUE="identifier='+a+'"/>';d+='<PARAM NAME=quality VALUE="autohigh"/>';d+='<PARAM NAME=wmode VALUE="'+b.Na+'"/>';d+='<PARAM NAME="allowScriptAccess" value="always"/>';
d+='<PARAM NAME="allowFullScreen" value="true"/>';return d+="</OBJECT>"};k.H=function(){return{path:(this.Ja?"https":"http")+"://cdn.flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,Na:"transparent"}};k.p=function(a){return Math.max(0,Math.ceil(a/100))};m.prototype=new r;r.prototype.g=function(a,b){var c=[""+this.F+this.K];c.push(a);c.push("0");c.push(this.O);c.push(this.random());b&&c.push(b);this.F&&((new Image).src=c.join("-"))};
r.prototype.random=function(a){return Math.floor(Math.random()*(a||1E9))};r.prototype.ia=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c,j)};window.ftPageFold_v4=function(a){a.breakingOut!==f&&(new l(a),a.campaignID&&27400>parseInt(a.campaignID,10)&&new m(a))};}());
